StudentBinaryFileExample:
	gcc -o StudentBinaryFileExample.out StudentBinaryFileMain.c StudentBinaryFile.c Struct_SerializeDeserialize.c Student.c


TextFileRead: TextFileRead.c
	gcc -o TextFileRead.out TextFileRead.c

TextFileWrite: TextFileWrite.c
	gcc -o TextFileWrite.out TextFileWrite.c

clean:
	rm -rf *.out *.a
